// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `RTAMonitor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __RTAMonitor_h__
#define __RTAMonitor_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace CTA
{

class RTAMonitor;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::CTA::RTAMonitor>&);
::IceProxy::Ice::Object* upCast(::IceProxy::CTA::RTAMonitor*);

}

}

namespace CTA
{

class RTAMonitor;
bool operator==(const RTAMonitor&, const RTAMonitor&);
bool operator<(const RTAMonitor&, const RTAMonitor&);
::Ice::Object* upCast(::CTA::RTAMonitor*);
typedef ::IceInternal::Handle< ::CTA::RTAMonitor> RTAMonitorPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::CTA::RTAMonitor> RTAMonitorPrx;
void __patch(RTAMonitorPtr&, const ::Ice::ObjectPtr&);

}

namespace CTA
{

struct Parameter
{
    ::Ice::Int apid;
    ::Ice::Double timestamp;
    ::Ice::Int type;
    ::Ice::Double value;
};

struct LogMessage
{
    ::Ice::Int apid;
    ::Ice::Double timestamp;
    ::std::string value;
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::CTA::Parameter>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 24;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::CTA::Parameter, S>
{
    static void write(S* __os, const ::CTA::Parameter& v)
    {
        __os->write(v.apid);
        __os->write(v.timestamp);
        __os->write(v.type);
        __os->write(v.value);
    }
};

template<class S>
struct StreamReader< ::CTA::Parameter, S>
{
    static void read(S* __is, ::CTA::Parameter& v)
    {
        __is->read(v.apid);
        __is->read(v.timestamp);
        __is->read(v.type);
        __is->read(v.value);
    }
};

template<>
struct StreamableTraits< ::CTA::LogMessage>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 13;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::CTA::LogMessage, S>
{
    static void write(S* __os, const ::CTA::LogMessage& v)
    {
        __os->write(v.apid);
        __os->write(v.timestamp);
        __os->write(v.value);
    }
};

template<class S>
struct StreamReader< ::CTA::LogMessage, S>
{
    static void read(S* __is, ::CTA::LogMessage& v)
    {
        __is->read(v.apid);
        __is->read(v.timestamp);
        __is->read(v.value);
    }
};

}

namespace CTA
{

class Callback_RTAMonitor_sendParameter_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RTAMonitor_sendParameter_Base> Callback_RTAMonitor_sendParameterPtr;

class Callback_RTAMonitor_sendLog_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RTAMonitor_sendLog_Base> Callback_RTAMonitor_sendLogPtr;

class Callback_RTAMonitor_registerApp_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RTAMonitor_registerApp_Base> Callback_RTAMonitor_registerAppPtr;

}

namespace IceProxy
{

namespace CTA
{

class RTAMonitor : virtual public ::IceProxy::Ice::Object
{
public:

    void sendParameter(const ::CTA::Parameter& param)
    {
        sendParameter(param, 0);
    }
    void sendParameter(const ::CTA::Parameter& param, const ::Ice::Context& __ctx)
    {
        sendParameter(param, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_sendParameter(const ::CTA::Parameter& param, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sendParameter(param, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_sendParameter(const ::CTA::Parameter& param, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendParameter(param, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendParameter(const ::CTA::Parameter& param, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sendParameter(param, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendParameter(const ::CTA::Parameter& param, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendParameter(param, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter& param)
    {
        return begin_sendParameter(param, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter& param, const ::Ice::Context& __ctx)
    {
        return begin_sendParameter(param, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter& param, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendParameter(param, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter& param, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendParameter(param, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter& param, const ::CTA::Callback_RTAMonitor_sendParameterPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendParameter(param, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter& param, const ::Ice::Context& __ctx, const ::CTA::Callback_RTAMonitor_sendParameterPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendParameter(param, &__ctx, __del, __cookie);
    }

    void end_sendParameter(const ::Ice::AsyncResultPtr&);
    
private:

    void sendParameter(const ::CTA::Parameter&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sendParameter(const ::CTA::Parameter&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void sendLog(const ::CTA::LogMessage& msg)
    {
        sendLog(msg, 0);
    }
    void sendLog(const ::CTA::LogMessage& msg, const ::Ice::Context& __ctx)
    {
        sendLog(msg, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_sendLog(const ::CTA::LogMessage& msg, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sendLog(msg, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_sendLog(const ::CTA::LogMessage& msg, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendLog(msg, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendLog(const ::CTA::LogMessage& msg, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sendLog(msg, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sendLog(const ::CTA::LogMessage& msg, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sendLog(msg, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage& msg)
    {
        return begin_sendLog(msg, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage& msg, const ::Ice::Context& __ctx)
    {
        return begin_sendLog(msg, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage& msg, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendLog(msg, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage& msg, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendLog(msg, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage& msg, const ::CTA::Callback_RTAMonitor_sendLogPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendLog(msg, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage& msg, const ::Ice::Context& __ctx, const ::CTA::Callback_RTAMonitor_sendLogPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendLog(msg, &__ctx, __del, __cookie);
    }

    void end_sendLog(const ::Ice::AsyncResultPtr&);
    
private:

    void sendLog(const ::CTA::LogMessage&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sendLog(const ::CTA::LogMessage&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void registerApp(::Ice::Int apid)
    {
        registerApp(apid, 0);
    }
    void registerApp(::Ice::Int apid, const ::Ice::Context& __ctx)
    {
        registerApp(apid, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_registerApp(::Ice::Int apid, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_registerApp(apid, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_registerApp(::Ice::Int apid, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_registerApp(apid, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_registerApp(::Ice::Int apid, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_registerApp(apid, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_registerApp(::Ice::Int apid, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_registerApp(apid, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int apid)
    {
        return begin_registerApp(apid, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int apid, const ::Ice::Context& __ctx)
    {
        return begin_registerApp(apid, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int apid, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_registerApp(apid, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int apid, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_registerApp(apid, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int apid, const ::CTA::Callback_RTAMonitor_registerAppPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_registerApp(apid, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int apid, const ::Ice::Context& __ctx, const ::CTA::Callback_RTAMonitor_registerAppPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_registerApp(apid, &__ctx, __del, __cookie);
    }

    void end_registerApp(const ::Ice::AsyncResultPtr&);
    
private:

    void registerApp(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_registerApp(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_secure(bool __secure) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_twoway() const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_oneway() const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_batchOneway() const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_datagram() const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_batchDatagram() const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_compress(bool __compress) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_timeout(int __timeout) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<RTAMonitor> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<RTAMonitor*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace CTA
{

class RTAMonitor : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void sendParameter(const ::CTA::Parameter&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void sendLog(const ::CTA::LogMessage&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void registerApp(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace CTA
{

class RTAMonitor : virtual public ::IceDelegate::CTA::RTAMonitor,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void sendParameter(const ::CTA::Parameter&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void sendLog(const ::CTA::LogMessage&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void registerApp(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace CTA
{

class RTAMonitor : virtual public ::IceDelegate::CTA::RTAMonitor,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void sendParameter(const ::CTA::Parameter&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void sendLog(const ::CTA::LogMessage&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void registerApp(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace CTA
{

class RTAMonitor : virtual public ::Ice::Object
{
public:

    typedef RTAMonitorPrx ProxyType;
    typedef RTAMonitorPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void sendParameter(const ::CTA::Parameter&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sendParameter(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void sendLog(const ::CTA::LogMessage&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sendLog(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void registerApp(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___registerApp(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const RTAMonitor& l, const RTAMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const RTAMonitor& l, const RTAMonitor& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace CTA
{

template<class T>
class CallbackNC_RTAMonitor_sendParameter : public Callback_RTAMonitor_sendParameter_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_RTAMonitor_sendParameter(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendParameter<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendParameter<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendParameter<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendParameter<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_RTAMonitor_sendParameter : public Callback_RTAMonitor_sendParameter_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_RTAMonitor_sendParameter(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendParameter<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendParameter<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendParameter<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_sendParameterPtr
newCallback_RTAMonitor_sendParameter(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendParameter<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_RTAMonitor_sendLog : public Callback_RTAMonitor_sendLog_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_RTAMonitor_sendLog(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendLog<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendLog<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendLog<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_sendLog<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_RTAMonitor_sendLog : public Callback_RTAMonitor_sendLog_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_RTAMonitor_sendLog(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendLog<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendLog<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendLog<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_sendLogPtr
newCallback_RTAMonitor_sendLog(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_sendLog<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_RTAMonitor_registerApp : public Callback_RTAMonitor_registerApp_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_RTAMonitor_registerApp(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_registerApp<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_registerApp<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_registerApp<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RTAMonitor_registerApp<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_RTAMonitor_registerApp : public Callback_RTAMonitor_registerApp_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_RTAMonitor_registerApp(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_registerApp<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_registerApp<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_registerApp<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RTAMonitor_registerAppPtr
newCallback_RTAMonitor_registerApp(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RTAMonitor_registerApp<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
